"""
optimizer.py — Parameter Optimization and Execution Grid.

This module orchestrates the complete grid search, executing backtests
across every possible combination of Assets, Timeframes, EMA Pairs, and Angle Thresholds.
"""

import logging
import pandas as pd
from typing import Dict, Any, List

from .config import EMA_PAIRS, ANGLE_THRESHOLDS, ASSETS, TIMEFRAMES, RANK_METRIC
from .backtest import run_backtest

log = logging.getLogger(__name__)


def run_full_sweep(
    data_store: Dict[str, Dict[str, pd.DataFrame]],
    initial_equity: float,
) -> Dict[str, Dict[str, Dict[Any, Dict[str, Any]]]]:
    """
    Executes the grid search backtest across all predefined parameters.

    Parameters
    ----------
    data_store : Dict[str, Dict[str, pd.DataFrame]]
        Nested dictionary holding OHLCV data. Format: data_store[asset][timeframe]
    initial_equity : float
        The initial capital allocated per backtest combination.

    Returns
    -------
    Dict
        A nested dictionary of results structured as:
        results[asset][timeframe][(fast_ema, slow_ema, threshold)] = metrics_dict
    """
    results: Dict[str, Dict[str, Dict[Any, Dict[str, Any]]]] = {}
    total_iterations: int = len(
        ASSETS) * len(TIMEFRAMES) * len(EMA_PAIRS) * len(ANGLE_THRESHOLDS)
    completed: int = 0

    for asset in ASSETS:
        results[asset] = {}
        for tf in TIMEFRAMES:
            results[asset][tf] = {}
            df: pd.DataFrame = data_store.get(asset, {}).get(tf)

            if df is None or df.empty:
                log.warning(
                    f"No data found for {asset} on {tf} timeframe. Skipping.")
                continue

            for (fast, slow) in EMA_PAIRS:
                for threshold in ANGLE_THRESHOLDS:
                    metrics: Dict[str, Any] = run_backtest(
                        df, fast, slow, threshold, initial_equity)
                    results[asset][tf][(fast, slow, threshold)] = metrics
                    completed += 1

                    if completed % 100 == 0:
                        log.info(
                            f"Optimization Progress: {completed}/{total_iterations} iterations complete.")

    log.info(f"Optimization Sweep Complete: {completed} backtests executed.")
    return results


def build_ranking_table(results: Dict[str, Dict[str, Dict[Any, Dict[str, Any]]]]) -> pd.DataFrame:
    """
    Aggregates all 1,440 combinations into a single ranked pandas DataFrame.

    Parameters
    ----------
    results : Dict
        The raw results dictionary generated by `run_full_sweep`.

    Returns
    -------
    pd.DataFrame
        A DataFrame containing all parameter sets ranked by the RANK_METRIC (descending).
    """
    rows: List[Dict[str, Any]] = []

    for asset, tf_dict in results.items():
        for tf, pair_dict in tf_dict.items():
            for (f, s, thr), m in pair_dict.items():
                if m.get("total_trades", 0) > 0:
                    rows.append({
                        "Market": asset,
                        "Timeframe": tf,
                        "EMA Pair": m.get("ema_pair", f"EMA({f},{s})"),
                        "Fast EMA": f,
                        "Slow EMA": s,
                        "Angle Threshold": thr,
                        "Trades": m.get("total_trades", 0),
                        "Win Rate (%)": m.get("win_rate", 0.0),
                        "Total Profit ($)": m.get("total_profit", 0.0),
                        "Avg Profit ($)": m.get("avg_profit", 0.0),
                        "Profit Factor": m.get("profit_factor", 0.0),
                        "Sharpe Ratio": m.get("sharpe_ratio", 0.0),
                        "Max Drawdown (%)": m.get("max_drawdown", 0.0),
                    })

    df: pd.DataFrame = pd.DataFrame(rows)
    if not df.empty:
        df = df.sort_values(by=[RANK_METRIC.replace('_', ' ').title().replace(
            'Profit', 'Profit ($)')], ascending=False, na_position='last')
        df = df.reset_index(drop=True)

    return df
